export const MAX_CONTAINER_THROUGHPUT = parseInt(process.env.AZURE_MAX_CONTAINER_THROUGHPUT ?? '400', 10)
export const MAX_DATABASE_THROUGHPUT = parseInt(process.env.AZURE_MAX_DATABASE_THROUGHPUT ?? '400', 10)
