#!/bin/sh
echo '#############################################'
echo '#                                           #'
echo '#  ⚠️  Remember to execute `rush lint:fix` ⚠️ #'
echo '#                                           #'
echo '#############################################'
