diff: true
node-option:
  - no-experimental-strip-types
require:
  - 'ts-node/register'
  - 'ts-patch/compiler'
extension:
  - ts
package: './package.json'
recursive: true
reporter: 'spec'
timeout: 5000
full-trace: true
bail: true
color: true
