name: Build

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/call-rush
      with:
        command: install

    - uses: ./.github/actions/call-rush
      with:
        command: build
