name: Run one integration test

inputs:
  integration-test:
    required: true
    type: string
  aws-region:
    default: 'us-east-1'
    required: false
    type: string
  azure-region:
    default: 'Central US'
    required: false
    type: string
  azure-publisher-email:
    default: 'noreply@booster.cloud'
    required: false
    type: string
  azure-publisher-name:
    default: 'Booster App'
    required: false
    type: string

  # Secrets
  bot-aws-access-key-id:
    required: false
    type: string
  bot-aws-secret-access-key:
    required: false
    type: string
  azure-clientid:
    required: false
    type: string
  azure-secret:
    required: false
    type: string
  azure-tenantid:
    required: false
    type: string
  azure-subscriptionid:
    required: false
    type: string
  azure-credentials:
    required: false
    type: string
  github_token:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    # If this was triggered by a /integration command, check out merge commit
    - name: Fork based /integration checkout
      id: fork-based-checkout
      if: github.event_name == 'repository_dispatch' &&
        github.event.client_payload.slash_command.sha != '' &&
        contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.sha)
      uses: actions/checkout@v3
      with:
        ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'

    - uses: ./.github/actions/build

    # This step will download the artifact named `integration-test-dependencies-${{ github.sha }}`
    # from the `Prepare Integration Tests` workflow into the `packages/framework-integration-tests/.booster`
    # folder.
    - name: Download integration test dependencies
      uses: actions/download-artifact@v2
      with:
        name: integration-test-dependencies-${{ github.sha }}
        path: packages/framework-integration-tests/.booster

    # Login if inputs.azure-credentials is set
    - name: Login to Azure
      if: ${{ inputs.azure-credentials }}
      uses: azure/login@v1.4.0
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Running ${{ inputs.integration-test }} integration test
      shell: bash
      run: cd packages/framework-integration-tests && node ../../common/scripts/install-run-rushx.js integration/${{ inputs.integration-test }} -v
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.bot-aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.bot-aws-secret-access-key }}
        AWS_REGION: ${{ inputs.aws-region }}
        AZURE_APP_ID: ${{ inputs.azure-clientid }}
        AZURE_SECRET: ${{ inputs.azure-secret }}
        AZURE_TENANT_ID: ${{ inputs.azure-tenantid }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.azure-subscriptionid }}
        REGION: ${{ inputs.azure-region }}
        publisherEmail: ${{ inputs.azure-publisher-email }}
        publisherName: ${{ inputs.azure-publisher-name }}}
        ARM_CLIENT_ID: ${{ inputs.azure-clientid }}
        ARM_CLIENT_SECRET: ${{ inputs.azure-secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.azure-subscriptionid }}
        ARM_TENANT_ID: ${{ inputs.azure-tenantid }}

    # Update the job status
    - uses: actions/github-script@v5
      needs: fork-based-checkout
      id: update-check-run
      if: always() && steps.fork-based-checkout.result == 'success'
      env:
        number: ${{ github.event.client_payload.pull_request.number }}
        job: ${{ github.job }}
        # Conveniently, job.status maps to https://developer.github.com/v3/checks/runs/#update-a-check-run
        conclusion: ${{ job.status }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { data: pull } = await github.rest.pulls.get({
            ...context.repo,
            pull_number: process.env.number
          });
          const ref = pull.head.sha;
          const { data: checks } = await github.rest.checks.listForRef({
            ...context.repo,
            ref
          });
          const check = checks.check_runs.filter(c => c.name === process.env.job);
          const { data: result } = await github.rest.checks.update({
            ...context.repo,
            check_run_id: check[0].id,
            status: 'completed',
            conclusion: process.env.conclusion
          });
          return result;
