diff: true
require: 'ts-node/register'
extension:
  - ts
package: './package.json'
recursive: true
reporter: 'spec'
timeout: 1200000
file:
  - './integration/providers/aws/setup.ts'
full-trace: true
# bail: true -- This option makes the test suite stop after the first failure. Might make sense to enable once tests are stable