diff: true
require: 'ts-node/register'
extension:
  - ts
package: './package.json'
recursive: true
reporter: 'spec'
timeout: 1500000
file:
  - './integration/providers/aws/functionality/setup.ts'
full-trace: true
bail: true