name: Run Integration Test

on:
  workflow_call:
    inputs:
      integration-test:
        required: true
        type: string
      aws-region:
        default: 'us-east-1'
        required: false
        type: string
      azure-region:
        default: 'Central US'
        required: false
        type: string
      azure-publisher-email:
        default: noreply@booster.cloud
        required: false
        type: string
      azure-publisher-name:
        default: Booster App
        required: false
        type: string

    secrets:
      BOT_AWS_ACCESS_KEY_ID:
        required: false
      BOT_AWS_SECRET_ACCESS_KEY:
        required: false
      AZURE_CLIENTID:
        required: false
      AZURE_SECRET:
        required: false
      AZURE_TENANTID:
        required: false
      AZURE_SUBSCRIPTIONID:
        required: false
      AZURE_CREDENTIALS:
        required: false

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Build
        uses: ./.github/workflows/re_checkout-build

      # This step will download the artifact named `integration-test-dependencies-${{ github.sha }}`
      # from the `Prepare Integration Tests` workflow into the `packages/framework-integration-tests/.booster`
      # folder.
      - name: Download integration test dependencies
        uses: actions/download-artifact@v2
        with:
          name: integration-test-dependencies-${{ github.sha }}
          path: packages/framework-integration-tests/.booster

      # Login if secrets.AZURE_CREDENTIALS is set
      - name: Login to Azure
        uses: azure/login@v1.4.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        if: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Running ${{ inputs.integration-test }} integration test
        run: cd packages/framework-integration-tests && node ../../common/scripts/install-run-rushx.js integration/${{ inputs.integration-test }} -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BOT_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BOT_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws-region }}
          AZURE_APP_ID: ${{ secrets.AZURE_CLIENTID }}
          AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANTID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTIONID }}
          REGION: ${{ inputs.azure-region }}
          publisherEmail: ${{ inputs.azure-publisher-email }}
          publisherName: ${{ inputs.azure-publisher-name }}}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENTID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTIONID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANTID }}
