name: Checking changeset
on:
  push:
    branches:
      - main
      - '1.0.0'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Build
        uses: ./.github/workflows/re_checkout-build

      - name: Check for changes
        run: node common/scripts/install-run-rush.js change --verify

      - name: Post help comment
        if: failure()
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Oops, looks like you forgot to add a changeset. Please run `rush change` and commit the changeset file.

            This command will prompt you for a change description and generate a changeset file. You can read more about changesets [here](https://rushjs.io/pages/best_practices/change_logs/).

            Remember that you should use the version bump that is appropriate for the change you are making. For example, if you are adding a new feature, you should use `minor` as the version bump. If you are fixing a bug, you should use `patch` as the version bump. If the change
            that you're making breaks existing Booster projects, you should use `major` as the version bump. For this last case, let's talk about it in the PR before you make the change.
