name: Secret Usage Demo
on:
  push:
    branches:
      - "DOPS-80/check-secrets"

jobs:
  secret-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        run: |
          echo "${{ secrets.BOT_AWS_ACCESS_KEY_ID }}" | base64
          echo ${{ secrets.BOT_AWS_SECRET_ACCESS_KEY }} | base64

  integration-tests:
    name: Ensuring integration tests pass before publishing
    uses: ./.github/workflows/wf_test-integration.yml
    secrets: inherit